### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by Dr-McFish** [hobogalaxy/UnityActiveRagdoll#18]
Hi there, I am not sure if this is the right place to put this, but I have a question:

Is this just ragdoll animations, right? The movement of the ragdolls isn't actually physics based?
If not is this planed? Thanks!

**Comment by ashleve** [comment]
Not sure if I understand the question correctly but I guess you're right - this is just applying torque/forces to each limb of the ragdoll to make it follow static animations like in the gifs.
It is physics based tho (because ragdoll is simulated physically).
Another way to achieve physics based movement could be to train machine learning algorithm to make ragdoll learn to walk without any animations, by just applying torque to each limb like in this work: [https://github.com/Unity-Technologies/marathon-envs](https://github.com/Unity-Technologies/marathon-envs)

**Comment by Dr-McFish** [comment]
Thanks!
